import sliderBenefit from "./modules/sliderBenefit";
import sliderServices from "./modules/sliderServices";
import btnCallModal from "./modules/btn_call";
import btnServicesModal from "./modules/btn_services";
import timerAction from "./modules/timerAction";
import validateForm from "./modules/validateForm";
import sendForm from "./modules/sendForm";
import sertificats from "./modules/documents";
import calc from "./modules/calcPay";
//import menu from "./module/menu";
//menu();

sliderBenefit();
sliderServices();
btnCallModal();
btnServicesModal();
timerAction("25 mart 2022");
validateForm();
sertificats();
calc();
sendForm("form1");
sendForm("form2");
sendForm("form3");
sendForm("form4");
sendForm("form5");
sendForm("form6");
sendForm("form7");