"use strict";

import menu from "./modules/menu";
import btnCallModal from "./modules/btn_call";
import btnServicesModal from "./modules/btn_services";
import sliderBenefits from "./modules/sliderBenefits";
import sliderServices from "./modules/sliderServices";
import timerAction from "./modules/timerAction";
import sertificats from "./modules/sertificats";
import smooth from "./modules/smooth";
import calc from "./modules/calc";
import sendForm from "./modules/sendForm";
import validateForm from "./modules/validateForm";

menu();
btnCallModal();
btnServicesModal();
sliderBenefits();
sliderServices();
timerAction("1 april 2022");
sertificats();
smooth();
calc();
sendForm("form1");
sendForm("form2");
sendForm("form3");
sendForm("form4");
sendForm("form5");
sendForm("form6");
sendForm("form7");
validateForm();